// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5
package oval_sc

import (
	"encoding/xml"
	"github.com/gocomply/scap/pkg/scap/models/oval"
	"github.com/gocomply/scap/pkg/scap/models/xml_dsig"
)

// Element
type OvalSystemCharacteristics struct {
	XMLName xml.Name `xml:oval_system_characteristics`

	Generator oval.GeneratorType `xml:"generator"`

	SystemInfo SystemInfoType `xml:"system_info"`

	CollectedObjects *CollectedObjectsType `xml:"collected_objects"`

	SystemData *SystemDataType `xml:"system_data"`

	Signature *xml_dsig.Signature `xml:"Signature"`
}

// Element
type Item struct {
	XMLName xml.Name `xml:item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr,omitempty"`

	Message []oval.MessageType `xml:"message"`
}

// XSD ComplexType declarations

type SystemInfoType struct {
	OsName string `xml:"os_name"`

	OsVersion string `xml:"os_version"`

	Architecture string `xml:"architecture"`

	PrimaryHostName string `xml:"primary_host_name"`

	Interfaces InterfacesType `xml:"interfaces"`

	InnerXml string `xml:",innerxml"`
}

type InterfacesType struct {
	Interface []InterfaceType `xml:"interface"`

	InnerXml string `xml:",innerxml"`
}

type InterfaceType struct {
	InterfaceName string `xml:"interface_name"`

	IpAddress string `xml:"ip_address"`

	MacAddress string `xml:"mac_address"`

	InnerXml string `xml:",innerxml"`
}

type CollectedObjectsType struct {
	Object []ObjectType `xml:"object"`

	InnerXml string `xml:",innerxml"`
}

type ObjectType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	VariableInstance *string `xml:"variable_instance,attr,omitempty"`

	Comment *string `xml:"comment,attr,omitempty"`

	Flag string `xml:"flag,attr"`

	Message []oval.MessageType `xml:"message"`

	VariableValue []VariableValueType `xml:"variable_value"`

	Reference []ReferenceType `xml:"reference"`

	InnerXml string `xml:",innerxml"`
}

type VariableValueType struct {
	VariableId string `xml:"variable_id,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type ReferenceType struct {
	ItemRef string `xml:"item_ref,attr"`

	InnerXml string `xml:",innerxml"`
}

type SystemDataType struct {
	Item []Item `xml:"item"`

	InnerXml string `xml:",innerxml"`
}

type ItemType struct {
	Id string `xml:"id,attr"`

	Status *string `xml:"status,attr,omitempty"`

	Message []oval.MessageType `xml:"message"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemSimpleBaseType struct {
	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type EntityItemComplexBaseType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemIPAddressType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemIPAddressStringType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemAnySimpleType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemBinaryType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemBoolType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemFloatType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemIntType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemStringType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemRecordType struct {
	Field []EntityItemFieldType `xml:"field"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemFieldType struct {
	Name string `xml:"name,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type EntityItemVersionType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemFilesetRevisionType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemIOSVersionType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemEVRStringType struct {
	InnerXml string `xml:",innerxml"`
}

type EntityItemDebianEVRStringType struct {
	InnerXml string `xml:",innerxml"`
}
