// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-definitions-5#windows
package win_def

import (
	"encoding/xml"
)

// Element
type AccesstokenTest struct {
	XMLName xml.Name `xml:accesstoken_test`
}

// Element
type AccesstokenObject struct {
	XMLName xml.Name `xml:accesstoken_object`
}

// Element
type AccesstokenState struct {
	XMLName xml.Name `xml:accesstoken_state`
}

// Element
type ActivedirectoryTest struct {
	XMLName xml.Name `xml:activedirectory_test`
}

// Element
type ActivedirectoryObject struct {
	XMLName xml.Name `xml:activedirectory_object`
}

// Element
type ActivedirectoryState struct {
	XMLName xml.Name `xml:activedirectory_state`
}

// Element
type Activedirectory57Test struct {
	XMLName xml.Name `xml:activedirectory57_test`
}

// Element
type Activedirectory57Object struct {
	XMLName xml.Name `xml:activedirectory57_object`
}

// Element
type Activedirectory57State struct {
	XMLName xml.Name `xml:activedirectory57_state`
}

// Element
type AuditeventpolicyTest struct {
	XMLName xml.Name `xml:auditeventpolicy_test`
}

// Element
type AuditeventpolicyObject struct {
	XMLName xml.Name `xml:auditeventpolicy_object`
}

// Element
type AuditeventpolicyState struct {
	XMLName xml.Name `xml:auditeventpolicy_state`
}

// Element
type AuditeventpolicysubcategoriesTest struct {
	XMLName xml.Name `xml:auditeventpolicysubcategories_test`
}

// Element
type AuditeventpolicysubcategoriesObject struct {
	XMLName xml.Name `xml:auditeventpolicysubcategories_object`
}

// Element
type AuditeventpolicysubcategoriesState struct {
	XMLName xml.Name `xml:auditeventpolicysubcategories_state`
}

// Element
type CmdletTest struct {
	XMLName xml.Name `xml:cmdlet_test`
}

// Element
type CmdletObject struct {
	XMLName xml.Name `xml:cmdlet_object`
}

// Element
type CmdletState struct {
	XMLName xml.Name `xml:cmdlet_state`
}

// Element
type DnscacheTest struct {
	XMLName xml.Name `xml:dnscache_test`
}

// Element
type DnscacheObject struct {
	XMLName xml.Name `xml:dnscache_object`
}

// Element
type DnscacheState struct {
	XMLName xml.Name `xml:dnscache_state`
}

// Element
type FileTest struct {
	XMLName xml.Name `xml:file_test`
}

// Element
type FileObject struct {
	XMLName xml.Name `xml:file_object`
}

// Element
type FileState struct {
	XMLName xml.Name `xml:file_state`
}

// Element
type Fileauditedpermissions53Test struct {
	XMLName xml.Name `xml:fileauditedpermissions53_test`
}

// Element
type Fileauditedpermissions53Object struct {
	XMLName xml.Name `xml:fileauditedpermissions53_object`
}

// Element
type Fileauditedpermissions53State struct {
	XMLName xml.Name `xml:fileauditedpermissions53_state`
}

// Element
type FileauditedpermissionsTest struct {
	XMLName xml.Name `xml:fileauditedpermissions_test`
}

// Element
type FileauditedpermissionsObject struct {
	XMLName xml.Name `xml:fileauditedpermissions_object`
}

// Element
type FileauditedpermissionsState struct {
	XMLName xml.Name `xml:fileauditedpermissions_state`
}

// Element
type Fileeffectiverights53Test struct {
	XMLName xml.Name `xml:fileeffectiverights53_test`
}

// Element
type Fileeffectiverights53Object struct {
	XMLName xml.Name `xml:fileeffectiverights53_object`
}

// Element
type Fileeffectiverights53State struct {
	XMLName xml.Name `xml:fileeffectiverights53_state`
}

// Element
type FileeffectiverightsTest struct {
	XMLName xml.Name `xml:fileeffectiverights_test`
}

// Element
type FileeffectiverightsObject struct {
	XMLName xml.Name `xml:fileeffectiverights_object`
}

// Element
type FileeffectiverightsState struct {
	XMLName xml.Name `xml:fileeffectiverights_state`
}

// Element
type GroupTest struct {
	XMLName xml.Name `xml:group_test`
}

// Element
type GroupObject struct {
	XMLName xml.Name `xml:group_object`
}

// Element
type GroupState struct {
	XMLName xml.Name `xml:group_state`
}

// Element
type GroupSidTest struct {
	XMLName xml.Name `xml:group_sid_test`
}

// Element
type GroupSidObject struct {
	XMLName xml.Name `xml:group_sid_object`
}

// Element
type GroupSidState struct {
	XMLName xml.Name `xml:group_sid_state`
}

// Element
type InterfaceTest struct {
	XMLName xml.Name `xml:interface_test`
}

// Element
type InterfaceObject struct {
	XMLName xml.Name `xml:interface_object`
}

// Element
type InterfaceState struct {
	XMLName xml.Name `xml:interface_state`
}

// Element
type JunctionTest struct {
	XMLName xml.Name `xml:junction_test`
}

// Element
type JunctionObject struct {
	XMLName xml.Name `xml:junction_object`
}

// Element
type JunctionState struct {
	XMLName xml.Name `xml:junction_state`
}

// Element
type LicenseTest struct {
	XMLName xml.Name `xml:license_test`
}

// Element
type LicenseObject struct {
	XMLName xml.Name `xml:license_object`
}

// Element
type LicenseState struct {
	XMLName xml.Name `xml:license_state`
}

// Element
type LockoutpolicyTest struct {
	XMLName xml.Name `xml:lockoutpolicy_test`
}

// Element
type LockoutpolicyObject struct {
	XMLName xml.Name `xml:lockoutpolicy_object`
}

// Element
type LockoutpolicyState struct {
	XMLName xml.Name `xml:lockoutpolicy_state`
}

// Element
type MetabaseTest struct {
	XMLName xml.Name `xml:metabase_test`
}

// Element
type MetabaseObject struct {
	XMLName xml.Name `xml:metabase_object`
}

// Element
type MetabaseState struct {
	XMLName xml.Name `xml:metabase_state`
}

// Element
type NtuserTest struct {
	XMLName xml.Name `xml:ntuser_test`
}

// Element
type NtuserObject struct {
	XMLName xml.Name `xml:ntuser_object`
}

// Element
type NtuserState struct {
	XMLName xml.Name `xml:ntuser_state`
}

// Element
type PasswordpolicyTest struct {
	XMLName xml.Name `xml:passwordpolicy_test`
}

// Element
type PasswordpolicyObject struct {
	XMLName xml.Name `xml:passwordpolicy_object`
}

// Element
type PasswordpolicyState struct {
	XMLName xml.Name `xml:passwordpolicy_state`
}

// Element
type PeheaderTest struct {
	XMLName xml.Name `xml:peheader_test`
}

// Element
type PeheaderObject struct {
	XMLName xml.Name `xml:peheader_object`
}

// Element
type PeheaderState struct {
	XMLName xml.Name `xml:peheader_state`
}

// Element
type PortTest struct {
	XMLName xml.Name `xml:port_test`
}

// Element
type PortObject struct {
	XMLName xml.Name `xml:port_object`
}

// Element
type PortState struct {
	XMLName xml.Name `xml:port_state`
}

// Element
type PrintereffectiverightsTest struct {
	XMLName xml.Name `xml:printereffectiverights_test`
}

// Element
type PrintereffectiverightsObject struct {
	XMLName xml.Name `xml:printereffectiverights_object`
}

// Element
type PrintereffectiverightsState struct {
	XMLName xml.Name `xml:printereffectiverights_state`
}

// Element
type ProcessTest struct {
	XMLName xml.Name `xml:process_test`
}

// Element
type ProcessObject struct {
	XMLName xml.Name `xml:process_object`
}

// Element
type ProcessState struct {
	XMLName xml.Name `xml:process_state`
}

// Element
type Process58Test struct {
	XMLName xml.Name `xml:process58_test`
}

// Element
type Process58Object struct {
	XMLName xml.Name `xml:process58_object`
}

// Element
type Process58State struct {
	XMLName xml.Name `xml:process58_state`
}

// Element
type RegistryTest struct {
	XMLName xml.Name `xml:registry_test`
}

// Element
type RegistryObject struct {
	XMLName xml.Name `xml:registry_object`
}

// Element
type RegistryState struct {
	XMLName xml.Name `xml:registry_state`
}

// Element
type Regkeyauditedpermissions53Test struct {
	XMLName xml.Name `xml:regkeyauditedpermissions53_test`
}

// Element
type Regkeyauditedpermissions53Object struct {
	XMLName xml.Name `xml:regkeyauditedpermissions53_object`
}

// Element
type Regkeyauditedpermissions53State struct {
	XMLName xml.Name `xml:regkeyauditedpermissions53_state`
}

// Element
type RegkeyauditedpermissionsTest struct {
	XMLName xml.Name `xml:regkeyauditedpermissions_test`
}

// Element
type RegkeyauditedpermissionsObject struct {
	XMLName xml.Name `xml:regkeyauditedpermissions_object`
}

// Element
type RegkeyauditedpermissionsState struct {
	XMLName xml.Name `xml:regkeyauditedpermissions_state`
}

// Element
type Regkeyeffectiverights53Test struct {
	XMLName xml.Name `xml:regkeyeffectiverights53_test`
}

// Element
type Regkeyeffectiverights53Object struct {
	XMLName xml.Name `xml:regkeyeffectiverights53_object`
}

// Element
type Regkeyeffectiverights53State struct {
	XMLName xml.Name `xml:regkeyeffectiverights53_state`
}

// Element
type RegkeyeffectiverightsTest struct {
	XMLName xml.Name `xml:regkeyeffectiverights_test`
}

// Element
type RegkeyeffectiverightsObject struct {
	XMLName xml.Name `xml:regkeyeffectiverights_object`
}

// Element
type RegkeyeffectiverightsState struct {
	XMLName xml.Name `xml:regkeyeffectiverights_state`
}

// Element
type ServiceTest struct {
	XMLName xml.Name `xml:service_test`
}

// Element
type ServiceObject struct {
	XMLName xml.Name `xml:service_object`
}

// Element
type ServiceState struct {
	XMLName xml.Name `xml:service_state`
}

// Element
type ServiceeffectiverightsTest struct {
	XMLName xml.Name `xml:serviceeffectiverights_test`
}

// Element
type ServiceeffectiverightsObject struct {
	XMLName xml.Name `xml:serviceeffectiverights_object`
}

// Element
type ServiceeffectiverightsState struct {
	XMLName xml.Name `xml:serviceeffectiverights_state`
}

// Element
type SharedresourceTest struct {
	XMLName xml.Name `xml:sharedresource_test`
}

// Element
type SharedresourceObject struct {
	XMLName xml.Name `xml:sharedresource_object`
}

// Element
type SharedresourceState struct {
	XMLName xml.Name `xml:sharedresource_state`
}

// Element
type SharedresourceauditedpermissionsTest struct {
	XMLName xml.Name `xml:sharedresourceauditedpermissions_test`
}

// Element
type SharedresourceauditedpermissionsObject struct {
	XMLName xml.Name `xml:sharedresourceauditedpermissions_object`
}

// Element
type SharedresourceauditedpermissionsState struct {
	XMLName xml.Name `xml:sharedresourceauditedpermissions_state`
}

// Element
type SharedresourceeffectiverightsTest struct {
	XMLName xml.Name `xml:sharedresourceeffectiverights_test`
}

// Element
type SharedresourceeffectiverightsObject struct {
	XMLName xml.Name `xml:sharedresourceeffectiverights_object`
}

// Element
type SharedresourceeffectiverightsState struct {
	XMLName xml.Name `xml:sharedresourceeffectiverights_state`
}

// Element
type SidTest struct {
	XMLName xml.Name `xml:sid_test`
}

// Element
type SidObject struct {
	XMLName xml.Name `xml:sid_object`
}

// Element
type SidState struct {
	XMLName xml.Name `xml:sid_state`
}

// Element
type SidSidTest struct {
	XMLName xml.Name `xml:sid_sid_test`
}

// Element
type SidSidObject struct {
	XMLName xml.Name `xml:sid_sid_object`
}

// Element
type SidSidState struct {
	XMLName xml.Name `xml:sid_sid_state`
}

// Element
type SystemmetricTest struct {
	XMLName xml.Name `xml:systemmetric_test`
}

// Element
type SystemmetricObject struct {
	XMLName xml.Name `xml:systemmetric_object`
}

// Element
type SystemmetricState struct {
	XMLName xml.Name `xml:systemmetric_state`
}

// Element
type UacTest struct {
	XMLName xml.Name `xml:uac_test`
}

// Element
type UacObject struct {
	XMLName xml.Name `xml:uac_object`
}

// Element
type UacState struct {
	XMLName xml.Name `xml:uac_state`
}

// Element
type UserTest struct {
	XMLName xml.Name `xml:user_test`
}

// Element
type UserObject struct {
	XMLName xml.Name `xml:user_object`
}

// Element
type UserState struct {
	XMLName xml.Name `xml:user_state`
}

// Element
type UserSid55Test struct {
	XMLName xml.Name `xml:user_sid55_test`
}

// Element
type UserSid55Object struct {
	XMLName xml.Name `xml:user_sid55_object`
}

// Element
type UserSid55State struct {
	XMLName xml.Name `xml:user_sid55_state`
}

// Element
type UserSidTest struct {
	XMLName xml.Name `xml:user_sid_test`
}

// Element
type UserSidObject struct {
	XMLName xml.Name `xml:user_sid_object`
}

// Element
type UserSidState struct {
	XMLName xml.Name `xml:user_sid_state`
}

// Element
type UserrightTest struct {
	XMLName xml.Name `xml:userright_test`
}

// Element
type UserrightObject struct {
	XMLName xml.Name `xml:userright_object`
}

// Element
type UserrightState struct {
	XMLName xml.Name `xml:userright_state`
}

// Element
type VolumeTest struct {
	XMLName xml.Name `xml:volume_test`
}

// Element
type VolumeObject struct {
	XMLName xml.Name `xml:volume_object`
}

// Element
type VolumeState struct {
	XMLName xml.Name `xml:volume_state`
}

// Element
type WmiTest struct {
	XMLName xml.Name `xml:wmi_test`
}

// Element
type WmiObject struct {
	XMLName xml.Name `xml:wmi_object`
}

// Element
type WmiState struct {
	XMLName xml.Name `xml:wmi_state`
}

// Element
type Wmi57Test struct {
	XMLName xml.Name `xml:wmi57_test`
}

// Element
type Wmi57Object struct {
	XMLName xml.Name `xml:wmi57_object`
}

// Element
type Wmi57State struct {
	XMLName xml.Name `xml:wmi57_state`
}

// Element
type WuaupdatesearcherTest struct {
	XMLName xml.Name `xml:wuaupdatesearcher_test`
}

// Element
type WuaupdatesearcherObject struct {
	XMLName xml.Name `xml:wuaupdatesearcher_object`
}

// Element
type WuaupdatesearcherState struct {
	XMLName xml.Name `xml:wuaupdatesearcher_state`
}

// XSD ComplexType declarations

type AccesstokenBehaviors string

type FileBehaviors string

type FileAuditPermissions53Behaviors string

type FileAuditPermissionsBehaviors string

type FileEffectiveRights53Behaviors string

type FileEffectiveRightsBehaviors string

type NTUserBehaviors string

type PrinterEffectiveRightsBehaviors string

type RegistryBehaviors string

type RegkeyAuditPermissions53Behaviors string

type RegkeyAuditPermissionsBehaviors string

type RegkeyEffectiveRights53Behaviors string

type RegkeyEffectiveRightsBehaviors string

type ServiceEffectiveRightsBehaviors string

type SharedResourceAuditedPermissionsBehaviors string

type SharedResourceEffectiveRightsBehaviors string

type SidBehaviors string

type SidSidBehaviors string

type WuaUpdateSearcherBehaviors string

type EntityStateAddrTypeType string

type EntityStateAdstypeType string

type EntityStateAuditType string

type EntityStateDriveTypeType string

type EntityStateInterfaceTypeType string

type EntityStateFileTypeType string

type EntityStateFileAttributeType string

type EntityObjectNamingContextType string

type EntityStateNamingContextType string

type EntityStateNTUserAccountTypeType string

type EntityStatePeTargetMachineType string

type EntityStatePeSubsystemType string

type EntityObjectProtocolType string

type EntityStateProtocolType string

type EntityObjectRegistryHiveType string

type EntityStateRegistryHiveType string

type EntityStateRegistryTypeType string

type EntityStateServiceControlsAcceptedType string

type EntityStateServiceCurrentStateType string

type EntityStateServiceStartTypeType string

type EntityStateServiceTypeType string

type EntityStateSharedResourceTypeType string

type EntityObjectSystemMetricIndexType string

type EntityStateSystemMetricIndexType string

type EntityObjectGUIDType string

type EntityStateGUIDType string

type EntityObjectCmdletVerbType string

type EntityStateCmdletVerbType string

type EntityStateWindowsViewType string

type EntityObjectUserRightType string

type EntityStateUserRightType string
