// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#freebsd
package freebsd_sc

import (
	"encoding/xml"
)

// Element
type PortinfoItem struct {
	XMLName xml.Name `xml:portinfo_item`
}

// XSD ComplexType declarations
