// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://cpe.mitre.org/language/2.0
package cpe

import (
	"encoding/xml"
)

// Element
type PlatformSpecification struct {
	XMLName xml.Name `xml:platform-specification`
}

// Element
type Platform struct {
	XMLName xml.Name `xml:platform`
}

// Element
type PlatformConfiguration struct {
	XMLName xml.Name `xml:platform-configuration`
}

// Element
type LogicalTest struct {
	XMLName xml.Name `xml:logical-test`
}

// Element
type FactRef struct {
	XMLName xml.Name `xml:fact-ref`
}

// Element
type CheckFactRef struct {
	XMLName xml.Name `xml:check-fact-ref`
}

// XSD ComplexType declarations

type PlatformSpecificationType string

type PlatformBaseType string

type PlatformType string

type LogicalTestType string

type FactRefType string

type CPEFactRefType string

type CheckFactRefType string

type TextType string
