// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://cpe.mitre.org/dictionary/2.0
package cpe_dict

import (
	"encoding/xml"
	"github.com/gocomply/scap/pkg/scap/models/cpe"
)

// Element
type CpeList struct {
	XMLName xml.Name `xml:cpe-list`

	Generator *GeneratorType `xml:"generator"`

	CpeItem []ItemType `xml:"cpe-item"`
}

// Element
type CpeItem struct {
	XMLName xml.Name `xml:cpe-item`

	Name cpe.Cpe22Type `xml:"name,attr"`

	Deprecated bool `xml:"deprecated,attr,omitempty"`

	DeprecatedBy cpe.Cpe22Type `xml:"deprecated_by,attr,omitempty"`

	DeprecationDate string `xml:"deprecation_date,attr,omitempty"`

	Title []TextType `xml:"title"`

	Notes []NotesType `xml:"notes"`

	References *ReferencesType `xml:"references"`

	Check []CheckType `xml:"check"`
}

// Element
type Reference struct {
	XMLName xml.Name `xml:reference`

	Href string `xml:"href,attr"`

	Text string `xml:",chardata"`
}

// XSD ComplexType declarations

type GeneratorType struct {
	XMLName xml.Name

	ProductName string `xml:"product_name"`

	ProductVersion string `xml:"product_version"`

	SchemaVersion float64 `xml:"schema_version"`

	Timestamp string `xml:"timestamp"`

	InnerXml string `xml:",innerxml"`
}

type ItemType struct {
	XMLName xml.Name

	Name cpe.Cpe22Type `xml:"name,attr"`

	Deprecated bool `xml:"deprecated,attr,omitempty"`

	DeprecatedBy cpe.Cpe22Type `xml:"deprecated_by,attr,omitempty"`

	DeprecationDate string `xml:"deprecation_date,attr,omitempty"`

	Title []TextType `xml:"title"`

	Notes []NotesType `xml:"notes"`

	References *ReferencesType `xml:"references"`

	Check []CheckType `xml:"check"`

	InnerXml string `xml:",innerxml"`
}

type ListType struct {
	XMLName xml.Name

	Generator *GeneratorType `xml:"generator"`

	CpeItem []ItemType `xml:"cpe-item"`

	InnerXml string `xml:",innerxml"`
}

type TextType struct {
	XMLName xml.Name

	XmlLang string `xml:"lang,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type NotesType struct {
	XMLName xml.Name

	XmlLang string `xml:"lang,attr"`

	Note []string `xml:",any"`

	InnerXml string `xml:",innerxml"`
}

type ReferencesType struct {
	XMLName xml.Name

	Reference []Reference `xml:",any"`

	InnerXml string `xml:",innerxml"`
}

type CheckType struct {
	XMLName xml.Name

	System string `xml:"system,attr"`

	Href string `xml:"href,attr,omitempty"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

// XSD SimpleType declarations
