// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-results-5
package oval_res

import (
	"encoding/xml"

	"github.com/gocomply/scap/pkg/scap/models/oval"

	"github.com/gocomply/scap/pkg/scap/models/oval_def"

	"github.com/gocomply/scap/pkg/scap/models/xml_dsig"
)

// Element
type OvalResults struct {
	XMLName xml.Name `xml:oval_results`

	Generator oval.GeneratorType `xml:"generator"`

	Directives DefaultDirectivesType `xml:"directives"`

	ClassDirectives ClassDirectivesType `xml:"class_directives"`

	OvalDefinitions oval_def.OvalDefinitions `xml:"oval_definitions"`

	Results ResultsType `xml:"results"`

	Signature xml_dsig.Signature `xml:"Signature"`
}

// XSD ComplexType declarations

type DirectivesType string

type DefaultDirectivesType string

type ClassDirectivesType string

type DirectiveType string

type ResultsType string

type SystemType string

type DefinitionsType string

type DefinitionType string

type CriteriaType string

type CriterionType string

type ExtendDefinitionType string

type TestsType string

type TestType string

type TestedItemType string

type TestedVariableType string
