// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-results-5
package oval_res

import (
	"encoding/xml"

	"github.com/gocomply/scap/pkg/scap/models/oval"

	"github.com/gocomply/scap/pkg/scap/models/oval_def"

	"github.com/gocomply/scap/pkg/scap/models/oval_sc"

	"github.com/gocomply/scap/pkg/scap/models/xml_dsig"
)

// Element
type OvalResults struct {
	XMLName xml.Name `xml:oval_results`

	Generator oval.GeneratorType `xml:"generator"`

	Directives DefaultDirectivesType `xml:"directives"`

	ClassDirectives ClassDirectivesType `xml:"class_directives"`

	OvalDefinitions oval_def.OvalDefinitions `xml:"oval_definitions"`

	Results ResultsType `xml:"results"`

	Signature xml_dsig.Signature `xml:"Signature"`
}

// XSD ComplexType declarations

type DirectivesType struct {
	DefinitionTrue DirectiveType `xml:"definition_true"`

	DefinitionFalse DirectiveType `xml:"definition_false"`

	DefinitionUnknown DirectiveType `xml:"definition_unknown"`

	DefinitionError DirectiveType `xml:"definition_error"`

	DefinitionNotEvaluated DirectiveType `xml:"definition_not_evaluated"`

	DefinitionNotApplicable DirectiveType `xml:"definition_not_applicable"`
}

type DefaultDirectivesType struct {
}

type ClassDirectivesType struct {
}

type DirectiveType struct {
}

type ResultsType struct {
	System []SystemType `xml:"system"`
}

type SystemType struct {
	Definitions DefinitionsType `xml:"definitions"`

	Tests TestsType `xml:"tests"`

	OvalSystemCharacteristics oval_sc.OvalSystemCharacteristics `xml:"oval_system_characteristics"`
}

type DefinitionsType struct {
	Definition []DefinitionType `xml:"definition"`
}

type DefinitionType struct {
	Message []oval.MessageType `xml:"message"`

	Criteria CriteriaType `xml:"criteria"`
}

type CriteriaType struct {
}

type CriterionType struct {
}

type ExtendDefinitionType struct {
}

type TestsType struct {
	Test []TestType `xml:"test"`
}

type TestType struct {
	Message []oval.MessageType `xml:"message"`

	TestedItem []TestedItemType `xml:"tested_item"`

	TestedVariable []TestedVariableType `xml:"tested_variable"`
}

type TestedItemType struct {
	Message []oval.MessageType `xml:"message"`
}

type TestedVariableType struct {
}
