// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint
package sp_sc

import (
	"encoding/xml"
)

// Element
type SpwebapplicationItem struct {
	XMLName xml.Name `xml:spwebapplication_item`
}

// Element
type SpgroupItem struct {
	XMLName xml.Name `xml:spgroup_item`
}

// Element
type SpwebItem struct {
	XMLName xml.Name `xml:spweb_item`
}

// Element
type SplistItem struct {
	XMLName xml.Name `xml:splist_item`
}

// Element
type SpantivirussettingsItem struct {
	XMLName xml.Name `xml:spantivirussettings_item`
}

// Element
type SpsiteadministrationItem struct {
	XMLName xml.Name `xml:spsiteadministration_item`
}

// Element
type SpsiteItem struct {
	XMLName xml.Name `xml:spsite_item`
}

// Element
type SpcrawlruleItem struct {
	XMLName xml.Name `xml:spcrawlrule_item`
}

// Element
type SpjobdefinitionItem struct {
	XMLName xml.Name `xml:spjobdefinition_item`
}

// Element
type Spjobdefinition510Item struct {
	XMLName xml.Name `xml:spjobdefinition510_item`
}

// Element
type BestbetItem struct {
	XMLName xml.Name `xml:bestbet_item`
}

// Element
type InfopolicycollItem struct {
	XMLName xml.Name `xml:infopolicycoll_item`
}

// Element
type SpdiagnosticsserviceItem struct {
	XMLName xml.Name `xml:spdiagnosticsservice_item`
}

// Element
type SpdiagnosticslevelItem struct {
	XMLName xml.Name `xml:spdiagnosticslevel_item`
}

// Element
type SppolicyfeatureItem struct {
	XMLName xml.Name `xml:sppolicyfeature_item`
}

// Element
type SppolicyItem struct {
	XMLName xml.Name `xml:sppolicy_item`
}

// XSD ComplexType declarations

type EntityItemUrlZoneType struct {
}

type EntityItemEventSeverityType struct {
}

type EntityItemTraceSeverityType struct {
}

type EntityItemPolicyFeatureStateType struct {
}

type EntityItemPolicyRoleType struct {
}
