// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for urn:oasis:names:tc:entity:xmlns:xml:catalog
package er

import (
	"encoding/xml"
)

// Element
type Catalog struct {
	XMLName xml.Name `xml:catalog`

	Public []Public `xml:"public"`

	System []System `xml:"system"`

	Uri []Uri `xml:"uri"`

	RewriteSystem []RewriteSystem `xml:"rewriteSystem"`

	RewriteURI []RewriteURI `xml:"rewriteURI"`

	UriSuffix []UriSuffix `xml:"uriSuffix"`

	SystemSuffix []SystemSuffix `xml:"systemSuffix"`

	DelegatePublic []DelegatePublic `xml:"delegatePublic"`

	DelegateSystem []DelegateSystem `xml:"delegateSystem"`

	DelegateURI []DelegateURI `xml:"delegateURI"`

	NextCatalog []NextCatalog `xml:"nextCatalog"`

	Group []Group `xml:"group"`
}

// Element
type Public struct {
	XMLName xml.Name `xml:public`
}

// Element
type System struct {
	XMLName xml.Name `xml:system`
}

// Element
type Uri struct {
	XMLName xml.Name `xml:uri`
}

// Element
type RewriteSystem struct {
	XMLName xml.Name `xml:rewriteSystem`
}

// Element
type RewriteURI struct {
	XMLName xml.Name `xml:rewriteURI`
}

// Element
type SystemSuffix struct {
	XMLName xml.Name `xml:systemSuffix`
}

// Element
type UriSuffix struct {
	XMLName xml.Name `xml:uriSuffix`
}

// Element
type DelegatePublic struct {
	XMLName xml.Name `xml:delegatePublic`
}

// Element
type DelegateSystem struct {
	XMLName xml.Name `xml:delegateSystem`
}

// Element
type DelegateURI struct {
	XMLName xml.Name `xml:delegateURI`
}

// Element
type NextCatalog struct {
	XMLName xml.Name `xml:nextCatalog`
}

// Element
type Group struct {
	XMLName xml.Name `xml:group`

	Public []Public `xml:"public"`

	System []System `xml:"system"`

	Uri []Uri `xml:"uri"`

	RewriteSystem []RewriteSystem `xml:"rewriteSystem"`

	RewriteURI []RewriteURI `xml:"rewriteURI"`

	UriSuffix []UriSuffix `xml:"uriSuffix"`

	SystemSuffix []SystemSuffix `xml:"systemSuffix"`

	DelegatePublic []DelegatePublic `xml:"delegatePublic"`

	DelegateSystem []DelegateSystem `xml:"delegateSystem"`

	DelegateURI []DelegateURI `xml:"delegateURI"`

	NextCatalog []NextCatalog `xml:"nextCatalog"`
}

// XSD ComplexType declarations
