// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris
package sol_sc

import (
	"encoding/xml"
)

// Element
type FacetItem struct {
	XMLName xml.Name `xml:facet_item`
}

// Element
type ImageItem struct {
	XMLName xml.Name `xml:image_item`
}

// Element
type IsainfoItem struct {
	XMLName xml.Name `xml:isainfo_item`
}

// Element
type NddItem struct {
	XMLName xml.Name `xml:ndd_item`
}

// Element
type PackageItem struct {
	XMLName xml.Name `xml:package_item`
}

// Element
type Package511Item struct {
	XMLName xml.Name `xml:package511_item`
}

// Element
type PackageavoidlistItem struct {
	XMLName xml.Name `xml:packageavoidlist_item`
}

// Element
type PackagecheckItem struct {
	XMLName xml.Name `xml:packagecheck_item`
}

// Element
type PackagefreezelistItem struct {
	XMLName xml.Name `xml:packagefreezelist_item`
}

// Element
type PackagepublisherItem struct {
	XMLName xml.Name `xml:packagepublisher_item`
}

// Element
type PatchItem struct {
	XMLName xml.Name `xml:patch_item`
}

// Element
type SmfItem struct {
	XMLName xml.Name `xml:smf_item`
}

// Element
type SmfpropertyItem struct {
	XMLName xml.Name `xml:smfproperty_item`
}

// Element
type VariantItem struct {
	XMLName xml.Name `xml:variant_item`
}

// Element
type VirtualizationinfoItem struct {
	XMLName xml.Name `xml:virtualizationinfo_item`
}

// XSD ComplexType declarations

type EntityItemClientUUIDType struct {
}

type EntityItemPermissionCompareType struct {
}

type EntityItemPublisherTypeType struct {
}

type EntityItemSmfServiceStateType struct {
}

type EntityItemV12NEnvType struct {
}

type EntityItemLDOMRoleType struct {
}
